In [27]:
# Initial imports
import pandas as pd
from pathlib import Path

In [28]:
# Load the NBA_GamesData.csv dataset.
file_path = "Resources/games_details.csv"
df = pd.read_csv(file_path)
#Inspect the data
df.head(25)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22000645,1610612754,IND,Indiana,203200,Justin Holiday,F,NaN,41:45,5.0,...,0.0,5.0,5.0,2.0,2.0,2.0,2.0,2.0,15.0,8.0
1,22000645,1610612754,IND,Indiana,1627734,Domantas Sabonis,F,NaN,35:06,5.0,...,2.0,9.0,11.0,1.0,3.0,0.0,5.0,6.0,17.0,-2.0
2,22000645,1610612754,IND,Indiana,1626167,Myles Turner,C,NaN,29:58,4.0,...,1.0,5.0,6.0,1.0,0.0,5.0,2.0,3.0,16.0,6.0
3,22000645,1610612754,IND,Indiana,1627747,Caris LeVert,G,NaN,34:42,5.0,...,0.0,3.0,3.0,3.0,1.0,0.0,0.0,1.0,13.0,1.0
4,22000645,1610612754,IND,Indiana,1627763,Malcolm Brogdon,G,NaN,40:35,4.0,...,3.0,3.0,6.0,10.0,1.0,0.0,2.0,1.0,12.0,6.0
5,22000645,1610612754,IND,Indiana,203926,Doug McDermott,NaN,NaN,19:01,7.0,...,2.0,5.0,7.0,2.0,0.0,0.0,1.0,4.0,15.0,2.0
6,22000645,1610612754,IND,Indiana,204456,T.J. McConnell,NaN,NaN,31:24,5.0,...,2.0,3.0,5.0,7.0,1.0,0.0,1.0,1.0,12.0,-1.0
7,22000645,1610612754,IND,Indiana,1628410,Edmond Sumner,NaN,NaN,11:54,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,3.0,-3.0
8,22000645,1610612754,IND,Indiana,203087,Jeremy Lamb,NaN,NaN,11:15,1.0,...,1.0,2.0,3.0,1.0,0.0,0.0,0.0,2.0,4.0,-5.0
9,22000645,1610612754,IND,Indiana,1629048,Goga Bitadze,NaN,NaN,9:20,1.0,...,1.0,2.0,3.0,0.0,0.0,2.0,0.0,1.0,2.0,3.0
10,22000645,1610612754,IND,Indiana,1628968,Brian Bowen II,NaN,DNP - Coach's Decision,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,22000645,1610612754,IND,Indiana,1628988,Aaron Holiday,NaN,DNP - Coach's Decision,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,22000645,1610612754,IND,Indiana,1629103,Kelan Martin,NaN,DNP - Coach's Decision,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,22000645,1610612754,IND,Indiana,203960,JaKarr Sampson,NaN,DNP - Coach's Decision,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,22000645,1610612754,IND,Indiana,1630199,Cassius Stanley,NaN,DNP - Coach's Decision,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,22000645,1610612748,MIA,Miami,202710,Jimmy Butler,F,NaN,41:41,7.0,...,6.0,9.0,15.0,7.0,0.0,0.0,2.0,3.0,21.0,-15.0
16,22000645,1610612748,MIA,Miami,203482,Kelly Olynyk,F,NaN,28:26,3.0,...,1.0,5.0,6.0,0.0,0.0,0.0,2.0,4.0,7.0,-17.0
17,22000645,1610612748,MIA,Miami,1628389,Bam Adebayo,C,NaN,36:20,11.0,...,2.0,8.0,10.0,2.0,2.0,3.0,4.0,1.0,29.0,22.0
18,22000645,1610612748,MIA,Miami,1629130,Duncan Robinson,G,NaN,39:36,5.0,...,0.0,5.0,5.0,5.0,0.0,1.0,0.0,2.0,13.0,15.0
19,22000645,1610612748,MIA,Miami,1629134,Kendrick Nunn,G,NaN,23:16,3.0,...,0.0,1.0,1.0,3.0,1.0,0.0,2.0,1.0,9.0,-9.0
20,22000645,1610612748,MIA,Miami,1630173,Precious Achiuwa,NaN,NaN,3:14,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-10.0
21,22000645,1610612748,MIA,Miami,1629639,Tyler Herro,NaN,NaN,36:11,4.0,...,1.0,4.0,5.0,4.0,0.0,1.0,1.0,1.0,11.0,-5.0
22,22000645,1610612748,MIA,Miami,1629216,Gabe Vincent,NaN,NaN,17:31,3.0,...,1.0,1.0,2.0,3.0,1.0,0.0,2.0,3.0,9.0,5.0
23,22000645,1610612748,MIA,Miami,2738,Andre Iguodala,NaN,NaN,19:32,1.0,...,1.0,1.0,2.0,3.0,2.0,0.0,1.0,1.0,2.0,17.0
24,22000645,1610612748,MIA,Miami,2772,Trevor Ariza,NaN,NaN,19:13,2.0,...,0.0,4.0,4.0,0.0,1.0,2.0,0.0,2.0,5.0,-18.0

In [41]:
#Fill NA values with zeros to represent DID NOT START, did not produce points, zero minutes, etc. 
#NaN values can be replaced as zeroes because zero means no impact.
df = df.fillna(0)
df.head(25)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22000645,1610612754,IND,Indiana,203200,Justin Holiday,F,0,41:45,5.0,...,0.0,5.0,5.0,2.0,2.0,2.0,2.0,2.0,15.0,8.0
1,22000645,1610612754,IND,Indiana,1627734,Domantas Sabonis,F,0,35:06,5.0,...,2.0,9.0,11.0,1.0,3.0,0.0,5.0,6.0,17.0,-2.0
2,22000645,1610612754,IND,Indiana,1626167,Myles Turner,C,0,29:58,4.0,...,1.0,5.0,6.0,1.0,0.0,5.0,2.0,3.0,16.0,6.0
3,22000645,1610612754,IND,Indiana,1627747,Caris LeVert,G,0,34:42,5.0,...,0.0,3.0,3.0,3.0,1.0,0.0,0.0,1.0,13.0,1.0
4,22000645,1610612754,IND,Indiana,1627763,Malcolm Brogdon,G,0,40:35,4.0,...,3.0,3.0,6.0,10.0,1.0,0.0,2.0,1.0,12.0,6.0
5,22000645,1610612754,IND,Indiana,203926,Doug McDermott,0,0,19:01,7.0,...,2.0,5.0,7.0,2.0,0.0,0.0,1.0,4.0,15.0,2.0
6,22000645,1610612754,IND,Indiana,204456,T.J. McConnell,0,0,31:24,5.0,...,2.0,3.0,5.0,7.0,1.0,0.0,1.0,1.0,12.0,-1.0
7,22000645,1610612754,IND,Indiana,1628410,Edmond Sumner,0,0,11:54,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,3.0,-3.0
8,22000645,1610612754,IND,Indiana,203087,Jeremy Lamb,0,0,11:15,1.0,...,1.0,2.0,3.0,1.0,0.0,0.0,0.0,2.0,4.0,-5.0
9,22000645,1610612754,IND,Indiana,1629048,Goga Bitadze,0,0,9:20,1.0,...,1.0,2.0,3.0,0.0,0.0,2.0,0.0,1.0,2.0,3.0
10,22000645,1610612754,IND,Indiana,1628968,Brian Bowen II,0,DNP - Coach's Decision,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,22000645,1610612754,IND,Indiana,1628988,Aaron Holiday,0,DNP - Coach's Decision,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,22000645,1610612754,IND,Indiana,1629103,Kelan Martin,0,DNP - Coach's Decision,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,22000645,1610612754,IND,Indiana,203960,JaKarr Sampson,0,DNP - Coach's Decision,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,22000645,1610612754,IND,Indiana,1630199,Cassius Stanley,0,DNP - Coach's Decision,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,22000645,1610612748,MIA,Miami,202710,Jimmy Butler,F,0,41:41,7.0,...,6.0,9.0,15.0,7.0,0.0,0.0,2.0,3.0,21.0,-15.0
16,22000645,1610612748,MIA,Miami,203482,Kelly Olynyk,F,0,28:26,3.0,...,1.0,5.0,6.0,0.0,0.0,0.0,2.0,4.0,7.0,-17.0
17,22000645,1610612748,MIA,Miami,1628389,Bam Adebayo,C,0,36:20,11.0,...,2.0,8.0,10.0,2.0,2.0,3.0,4.0,1.0,29.0,22.0
18,22000645,1610612748,MIA,Miami,1629130,Duncan Robinson,G,0,39:36,5.0,...,0.0,5.0,5.0,5.0,0.0,1.0,0.0,2.0,13.0,15.0
19,22000645,1610612748,MIA,Miami,1629134,Kendrick Nunn,G,0,23:16,3.0,...,0.0,1.0,1.0,3.0,1.0,0.0,2.0,1.0,9.0,-9.0
20,22000645,1610612748,MIA,Miami,1630173,Precious Achiuwa,0,0,3:14,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-10.0
21,22000645,1610612748,MIA,Miami,1629639,Tyler Herro,0,0,36:11,4.0,...,1.0,4.0,5.0,4.0,0.0,1.0,1.0,1.0,11.0,-5.0
22,22000645,1610612748,MIA,Miami,1629216,Gabe Vincent,0,0,17:31,3.0,...,1.0,1.0,2.0,3.0,1.0,0.0,2.0,3.0,9.0,5.0
23,22000645,1610612748,MIA,Miami,2738,Andre Iguodala,0,0,19:32,1.0,...,1.0,1.0,2.0,3.0,2.0,0.0,1.0,1.0,2.0,17.0
24,22000645,1610612748,MIA,Miami,2772,Trevor Ariza,0,0,19:13,2.0,...,0.0,4.0,4.0,0.0,1.0,2.0,0.0,2.0,5.0,-18.0

In [46]:
#Drop TEAM_ABBREVIATION, TEAM_CITY, PLAYER_NAME
df = df.drop(['TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_NAME'], axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 602767 entries, 0 to 602766
Data columns (total 25 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   GAME_ID         602767 non-null  int64
 1   TEAM_ID         602767 non-null  int64
 2   PLAYER_ID       602767 non-null  int64
 3   START_POSITION  602767 non-null  object
 4   COMMENT         602767 non-null  object
 5   MIN             602767 non-null  object
 6   FGM             602767 non-null  float64
 7   FGA             602767 non-null  float64
 8   FG_PCT          602767 non-null  float64
 9   FG3M            602767 non-null  float64
 10  FG3A            602767 non-null  float64
 11  FG3_PCT         602767 non-null  float64
 12  FTM             602767 non-null  float64
 13  FTA             602767 non-null  float64
 14  FT_PCT          602767 non-null  float64
 15  OREB            602767 non-null  float64
 16  DREB            602767 non-null  float64
 17  REB             602767 non-null  float64
 18  AST             602767 non-null  float64
 19  STL             602767 non-null  float64
 20  BLK             602767 non-null  float64
 21  TO              602767 non-null  float64
 22  PF              602767 non-null  float64
 23  PTS             602767 non-null  float64
 24  PLUS_MINUS      602767 non-null  float64
dtypes: float64(19), int64(3), object(3)
memory usage: 115.0+ MB

In [52]:
#Convert minutes to date time format
df['MIN'].str.split(':').apply(lambda x: int(x[0]) + int(x[1])/60)
df

#s = pd.Series(df['MIN'])
#v = s.str.split(':', expand=True).astype(float)
#s = pd.to_timedelta(v[0], unit='m') + pd.to_timedelta(v[1], unit='s')
#s

#MIN = s.dt.min
#print(MIN)
#time.hour * 60 + time.minute

TypeError: 'float' object is not subscriptable

In [51]:
df['MIN'] = df['MIN'].astype('datetime64[D]')

ParserError: hour must be in 0..23: 41:45

In [ ]:
#Get Dummy variables for START_POSITION
pd.get_dummies(df, columns=['START_POSITION'])

In [4]:
# Home Team has @ sign after name, so split match up column into three columns
# Home team have rows with @ symbol and away teams do not
df[['Team_1', 'symbol', 'Team_2']] = df.MATCHUP.str.split(expand=True)

In [9]:
#Drop unnecessary home team columns
df_home = df_home.drop(['MATCHUP', 'WL', 'Team_1', 'symbol', 'Team_2'], axis=1)
#Drop unnecessary away team columns
df_away = df_away.drop(['MATCHUP', 'WL', 'Team_1', 'symbol', 'Team_2'], axis=1)

In [10]:
df2 = df_home.merge(df_away, how = 'outer', on = 'GAME_ID')

In [14]:
#Change Game_Date Column to Date Time Format
df2['GAME_DATE'] = df['GAME_DATE'].astype('datetime64[D]')
#Check Column Formats
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14883 entries, 0 to 15003
Data columns (total 44 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SEASON_ID        14883 non-null  float64
 1   HOME_TEAM_ID     14883 non-null  float64
 2   GAME_ID          14883 non-null  int64
 3   GAME_DATE        14883 non-null  datetime64[ns]
 4   HOME_PTS         14883 non-null  float64
 5   HOME_FGM         14883 non-null  float64
 6   HOME_FGA         14883 non-null  float64
 7   HOME_FG_PCT      14883 non-null  float64
 8   HOME_FG3M        14883 non-null  float64
 9   HOME_FG3A        14883 non-null  float64
 10  HOME_FG3_PCT     14883 non-null  float64
 11  HOME_FTM         14883 non-null  float64
 12  HOME_FTA         14883 non-null  float64
 13  HOME_FT_PCT      14883 non-null  float64
 14  HOME_OREB        14883 non-null  float64
 15  HOME_DREB        14883 non-null  float64
 16  HOME_REB         14883 non-null  float64
 17  HOME_AST         14883 non-null  float64
 18  HOME_STL         14883 non-null  float64
 19  HOME_BLK         14883 non-null  float64
 20  HOME_TOV         14883 non-null  float64
 21  HOME_PF          14883 non-null  float64
 22  HOME_PLUS_MINUS  14883 non-null  float64
 23  HOME_WIN         14883 non-null  object
 24  AWAY_TEAM_ID     14883 non-null  float64
 25  AWAY_PTS         14883 non-null  float64
 26  AWAY_FGM         14883 non-null  float64
 27  AWAY_FGA         14883 non-null  float64
 28  AWAY_FG_PCT      14883 non-null  float64
 29  AWAY_FG3M        14883 non-null  float64
 30  AWAY_FG3A        14883 non-null  float64
 31  AWAY_FG3_PCT     14883 non-null  float64
 32  AWAY_FTM         14883 non-null  float64
 33  AWAY_FTA         14883 non-null  float64
 34  AWAY_FT_PCT      14883 non-null  float64
 35  AWAY_OREB        14883 non-null  float64
 36  AWAY_DREB        14883 non-null  float64
 37  AWAY_REB         14883 non-null  float64
 38  AWAY_AST         14883 non-null  float64
 39  AWAY_STL         14883 non-null  float64
 40  AWAY_BLK         14883 non-null  float64
 41  AWAY_TOV         14883 non-null  float64
 42  AWAY_PF          14883 non-null  float64
 43  AWAY_PLUS_MINUS  14883 non-null  float64
dtypes: datetime64[ns](1), float64(41), int64(1), object(1)
memory usage: 5.1+ MB

In [15]:
#Double check for duplicate values
df2.drop_duplicates(subset=['GAME_ID'], keep='first')
#Convert Home_Win column from string to integer
df2["HOME_WIN"] = df2["HOME_WIN"].astype(str).astype(int)
#Check Column Formats and if there are any duplicate entries: no duplicates as both checks resulted in 14,883 entries.
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14883 entries, 0 to 15003
Data columns (total 44 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SEASON_ID        14883 non-null  float64
 1   HOME_TEAM_ID     14883 non-null  float64
 2   GAME_ID          14883 non-null  int64
 3   GAME_DATE        14883 non-null  datetime64[ns]
 4   HOME_PTS         14883 non-null  float64
 5   HOME_FGM         14883 non-null  float64
 6   HOME_FGA         14883 non-null  float64
 7   HOME_FG_PCT      14883 non-null  float64
 8   HOME_FG3M        14883 non-null  float64
 9   HOME_FG3A        14883 non-null  float64
 10  HOME_FG3_PCT     14883 non-null  float64
 11  HOME_FTM         14883 non-null  float64
 12  HOME_FTA         14883 non-null  float64
 13  HOME_FT_PCT      14883 non-null  float64
 14  HOME_OREB        14883 non-null  float64
 15  HOME_DREB        14883 non-null  float64
 16  HOME_REB         14883 non-null  float64
 17  HOME_AST         14883 non-null  float64
 18  HOME_STL         14883 non-null  float64
 19  HOME_BLK         14883 non-null  float64
 20  HOME_TOV         14883 non-null  float64
 21  HOME_PF          14883 non-null  float64
 22  HOME_PLUS_MINUS  14883 non-null  float64
 23  HOME_WIN         14883 non-null  int64
 24  AWAY_TEAM_ID     14883 non-null  float64
 25  AWAY_PTS         14883 non-null  float64
 26  AWAY_FGM         14883 non-null  float64
 27  AWAY_FGA         14883 non-null  float64
 28  AWAY_FG_PCT      14883 non-null  float64
 29  AWAY_FG3M        14883 non-null  float64
 30  AWAY_FG3A        14883 non-null  float64
 31  AWAY_FG3_PCT     14883 non-null  float64
 32  AWAY_FTM         14883 non-null  float64
 33  AWAY_FTA         14883 non-null  float64
 34  AWAY_FT_PCT      14883 non-null  float64
 35  AWAY_OREB        14883 non-null  float64
 36  AWAY_DREB        14883 non-null  float64
 37  AWAY_REB         14883 non-null  float64
 38  AWAY_AST         14883 non-null  float64
 39  AWAY_STL         14883 non-null  float64
 40  AWAY_BLK         14883 non-null  float64
 41  AWAY_TOV         14883 non-null  float64
 42  AWAY_PF          14883 non-null  float64
 43  AWAY_PLUS_MINUS  14883 non-null  float64
dtypes: datetime64[ns](1), float64(41), int64(2)
memory usage: 5.1 MB

In [16]:
#Save file to CSV
df2.to_csv('Resources/games_final.csv', index=True)